FROM rust:latest

# Add these flags to reduce memory usage
ENV RUSTFLAGS="-C codegen-units=1"

# Limit the number of parallel compilation jobs
ENV CARGO_BUILD_JOBS=1

WORKDIR /app

# Install cargo-watch for hot reloading
RUN cargo install cargo-watch

# Copy everything into the container
COPY . .

EXPOSE 3000

CMD ["cargo", "watch", "-x", "run"]
