//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::content::Entity as Content;
pub use super::images::Entity as Images;
pub use super::pages::Entity as Pages;
pub use super::roles::Entity as Roles;
pub use super::users::Entity as Users;
